In [28]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df['Message'], df.Spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train)

In [14]:
type(X_train_cv)

scipy.sparse._csr.csr_matrix

In [21]:
cv.get_feature_names_out()[1000:1050]

array(['anywhere', 'aom', 'apart', 'apartment', 'apes', 'apeshit',
       'aphex', 'apnt', 'apo', 'apologetic', 'apologise', 'apologize',
       'apology', 'app', 'apparently', 'appeal', 'appendix',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'approve', 'approved',
       'approx', 'apps', 'appt', 'appy', 'april', 'aproach', 'apt',
       'aptitude', 'aquarius', 'ar', 'arabian', 'arcade', 'archive',
       'ard', 'are', 'area', 'aren', 'arent'], dtype=object)

In [22]:
cv.vocabulary_

{'best': 1334,
 'line': 4183,
 'said': 5957,
 'in': 3691,
 'love': 4282,
 'will': 7646,
 'wait': 7472,
 'till': 7008,
 'the': 6917,
 'day': 2205,
 'can': 1641,
 'forget': 2980,
 'or': 5048,
 'realize': 5682,
 'that': 6913,
 'cannot': 1652,
 'me': 4468,
 'gn': 3199,
 'very': 7390,
 'hurting': 3610,
 'meaningful': 4473,
 'lines': 4186,
 'ever': 2699,
 'compromised': 1962,
 'everything': 2708,
 'for': 2972,
 'my': 4724,
 'but': 1588,
 'at': 1118,
 'end': 2615,
 'gud': 3306,
 'mornin': 4648,
 'are': 1046,
 'you': 7839,
 'free': 3019,
 'now': 4911,
 'call': 1618,
 'ok': 4990,
 'waliking': 7479,
 'ard': 1045,
 'do': 2399,
 'wan': 7491,
 'buy': 1593,
 'anything': 995,
 'go': 3203,
 'ur': 7318,
 'house': 3567,
 'look': 4252,
 'da': 2166,
 'lib': 4150,
 'got': 3244,
 'stuff': 6637,
 'havent': 3405,
 'finish': 2892,
 'yet': 7827,
 'send': 6089,
 'this': 6959,
 'to': 7043,
 'friends': 3041,
 'and': 956,
 'receive': 5701,
 'something': 6394,
 'about': 750,
 'voice': 7435,
 'how': 3571,
 'is': 3800

In [24]:
cv.get_feature_names_out()[2980]

'forget'

In [25]:
X_train_np = X_train_cv.toarray()

In [27]:
X_train_np[0:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
np.where(X_train_np[0]!=0)

(array([1334, 1641, 1652, 2205, 2980, 3199, 3691, 4183, 4282, 4468, 5048,
        5682, 5957, 6913, 6917, 7008, 7472, 7646], dtype=int64),)

In [31]:
X_train[:4]

2382    Best line said in Love: . "I will wait till th...
1670    Very hurting n meaningful lines ever: "I compr...
495                      Are you free now?can i call now?
2217    OK i'm waliking ard now... Do u wan me 2 buy a...
Name: Message, dtype: object

In [32]:
X_train[:4][2382]

'Best line said in Love: . "I will wait till the day I can forget u Or The day u realize that u cannot forget me."... Gn'

In [35]:
cv.get_feature_names_out()[1652]

'cannot'

In [ ]:
# Model building (Naive Bayes classifier)

In [36]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_cv, y_train)

MultinomialNB()

In [37]:
X_test_cv = cv.transform(X_test)

In [38]:
y_pred = nb.predict(X_test_cv)

In [41]:
from sklearn.metrics import classification_report

print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       960
           1       0.90      0.95      0.92       155

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [51]:
emails =['Hello, how are you doing? Its been long since we caught up last time. Hope you are doing good',
        'Hurrah!! you won $ 287655434 prize and its waiting in your nostro. grab the bonanza']
cn = cv.transform(emails)
nb.predict(cn)

array([0, 1], dtype=int64)

In [52]:
# alternative method

from sklearn.pipeline import Pipeline

clpip = Pipeline([
    ('vectorizer' , CountVectorizer()),
    ('nb', MultinomialNB())
])

In [53]:
clpip.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
print(classification_report(y_test, clpip.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       952
           1       0.95      0.90      0.92       163

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

