In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [5]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [6]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [14]:
Text_test = ['nice movie screenplay and story', 'I love Python for datascience']
Text_preprocessed = bert_preprocess_model(Text_test)
Text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [15]:
Text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [18]:
Text_preprocessed['input_word_ids']
#CLF nice movie screenplay and story SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  9000,  1998,  2466,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [20]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(Text_preprocessed)

In [21]:
bert_results.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'pooled_output', 'default'])

In [22]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 1.24771565e-01, -8.00514966e-03, -8.95619988e-02, ...,
           1.84695035e-01, -7.96275586e-03, -1.05450071e-01],
         [ 1.23708713e+00,  7.72721648e-01,  8.47651005e-01, ...,
           7.79175103e-01, -3.30121994e-01, -2.47468144e-01],
         [-2.17009187e-01,  4.99696553e-01, -5.11289835e-01, ...,
           7.01183200e-01,  4.14565027e-01, -1.08740389e+00],
         ...,
         [-3.41359824e-02, -3.61697018e-01,  6.49232864e-01, ...,
           5.28269351e-01, -1.45099342e-01,  2.00414360e-01],
         [-1.24135330e-01, -3.97117406e-01,  5.44129610e-01, ...,
           5.70586503e-01, -7.59092793e-02,  7.43505955e-02],
         [ 1.15268826e-02, -3.16819012e-01,  5.71828008e-01, ...,
           8.38911772e-01, -3.72395486e-01,  3.80031765e-04]],
 
        [[ 1.63430825e-01,  4.06821482e-02, -2.51685902e-02, ...,
           4.42306474e-02,  1.38271153e-01,  1.42435096e-02],
         [ 5.88231564e-01,  7.2

In [23]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.912192  , -0.583184  , -0.8798037 , ..., -0.68628144,
        -0.6546358 ,  0.9087185 ],
       [-0.85725963, -0.33429474, -0.18839851, ..., -0.05977561,
        -0.6319231 ,  0.8671609 ]], dtype=float32)>

In [24]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.3003137 , -0.2709114 , -0.13316523, ..., -0.60919225,
          0.1683591 ,  0.2784799 ],
        [ 0.20763932, -0.52212095,  0.4465589 , ..., -0.3249306 ,
          0.6503117 , -0.07211627],
        [ 0.61667943, -0.20607725, -0.14262787, ..., -0.5287452 ,
         -0.03861109, -0.69125307],
        ...,
        [ 0.0654399 , -0.4002915 ,  0.45074096, ..., -0.25864553,
          0.02496833, -0.1310437 ],
        [-0.04195144, -0.38677663,  0.4329288 , ..., -0.3150604 ,
          0.03580529, -0.09073164],
        [ 0.0796821 , -0.37882018,  0.48185438, ..., -0.23821965,
          0.03116701, -0.13247839]],

       [[ 0.08164758,  0.15477955, -0.06713456, ..., -0.13856089,
          0.04363997,  0.59982973],
        [ 0.52732444,  0.16357826, -0.6187974 , ..., -0.10579126,
          0.58930534,  0.725133  ],
        [ 1.3174883 ,  0.9888726 ,  0.13870761, ...,  0.1982657 ,
          0.456407  ,  0.51699084],
        ...,

In [25]:
bert_results['default']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.912192  , -0.583184  , -0.8798037 , ..., -0.68628144,
        -0.6546358 ,  0.9087185 ],
       [-0.85725963, -0.33429474, -0.18839851, ..., -0.05977561,
        -0.6319231 ,  0.8671609 ]], dtype=float32)>