In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [4]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [10]:
one_hot("just loved it",200) # this unique numbers will be converted into 0s and 1s by the neural network Keras layers

[61, 179, 174]

In [16]:
vocab_size = 30
Encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
Encoded_reviews

[[17, 28],
 [2, 24],
 [12, 21],
 [10, 7, 17],
 [26, 23, 2],
 [11, 28],
 [16, 23, 19],
 [28, 4],
 [28, 2],
 [1, 4]]

In [17]:
max_length = 3
padded_reviews = pad_sequences(Encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[17, 28,  0],
       [ 2, 24,  0],
       [12, 21,  0],
       [10,  7, 17],
       [26, 23,  2],
       [11, 28,  0],
       [16, 23, 19],
       [28,  4,  0],
       [28,  2,  0],
       [ 1,  4,  0]])

In [29]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))  # In this step 4x30 (mxn) embedding vector matrix is multiplied with 30x30 (nxp) one hot encoded vector matrix and produces the 4x30 (mxp) embeded weights matrix
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [30]:
X = padded_reviews
y = sentiment

In [31]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.fit(X, y, epochs=50, verbose=0)

In [33]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 141ms/step - loss: 0.6395 - accuracy: 0.9000


In [36]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [39]:
model.get_layer('embedding').get_weights()[0]

array([[-0.06875117, -0.00459441,  0.06740481, -0.00716244],
       [-0.01153784,  0.01173036,  0.07051674, -0.0984806 ],
       [ 0.08650373, -0.0762645 , -0.07254013,  0.03763349],
       [-0.02189356,  0.04527435, -0.00609698,  0.03980602],
       [ 0.06044866, -0.09216749,  0.00471115,  0.07071085],
       [ 0.01844757,  0.00897545,  0.03153353,  0.03028587],
       [-0.03377785, -0.01382308,  0.04869263,  0.01103512],
       [-0.05328221,  0.01691277, -0.00625883, -0.07595699],
       [ 0.0162778 , -0.04489131, -0.04250621,  0.00242589],
       [ 0.01754551,  0.02995079, -0.01255991,  0.00326686],
       [ 0.06552533, -0.0603035 , -0.09876905,  0.03496297],
       [-0.08443156,  0.0652362 ,  0.08101337, -0.00101333],
       [ 0.08784972, -0.06186568, -0.01098832,  0.02395772],
       [-0.01972667,  0.04656675, -0.02000442,  0.00936203],
       [-0.04197785,  0.01441954, -0.0245476 ,  0.03036846],
       [-0.04536804,  0.00060543,  0.00922988, -0.01848515],
       [-0.04871845,  0.

In [40]:
weights[11]

array([-0.08443156,  0.0652362 ,  0.08101337, -0.00101333], dtype=float32)

In [41]:
weights[3]

array([-0.02189356,  0.04527435, -0.00609698,  0.03980602], dtype=float32)